wandb_version: 1

defense:
  desc: null
  value:
    threat_model: std
    dataset: cifar10
    batch_size: 256
    lr: 0.1
    lambda_mse: 10
    save_mat: false
    n_epochs: 100
    print_every: 10
    atk_type: mufia
    block_size: 32
    model_name: resnet50
    parallel: false
    verbose: false
    sim_loss: cosine
    kappa: 0.9
    save_name: test_mufia_std_resnet50_iter_100_reg_10_kappa_0.9.pt
    save_dir: /SCRATCH2/machiraj/quantize_mats/
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.1
    framework: huggingface
    huggingface_version: 4.29.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688650786.087127
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.15.1
      6: 4.29.0.dev0
      8:
      - 5
